services:
  elastic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      # 아래 설정은 개발/테스트 환경에서 간단하게 테스트하기 위한 옵션 (운영 환경에서는 설정하면 안 됨)
      - discovery.type=single-node # 단일 노드 (지금은 알 필요 없음)
      - xpack.security.enabled=false # 보안 설정
      - xpack.security.http.ssl.enabled=false # 보안 설정
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk_network
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.4
    container_name: logstash
    ports:
      - "9600:9600" # Logstash 모니터링 API
      - "5044:5044"
    volumes:
      - ../logstash/pipeline:/usr/share/logstash/pipeline
      - ../logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - LS_JAVA_OPTS="-Xms1g -Xmx1g"
    depends_on:
      elastic:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9600/_node/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m # Logstash는 시작 시간이 길기 때문에 충분한 시간을 줍니다.
    networks:
      - elk_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.4
    container_name: filebeat
    user: root
    command: [ "filebeat", "-e", "--strict.perms=false" ]
    volumes:
      - ../filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - filebeat_data:/usr/share/filebeat/data
    environment:
      - LOGSTASH_HOSTS=logstash:5044
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      logstash:
        condition: service_healthy
    networks:
      - elk_network
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4 # 8.17.4 버전
    container_name: kibana
    ports:
      - "5601:5601" # 5601번 포트에서 kibana 실행
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200 # kibana가 통신할 Elasticsearch 주소 알려주기
      - TZ=Asia/Seoul
      - NODE_OPTIONS="--max-old-space-size=1024" #
    depends_on:
      elastic:
        condition: service_healthy
    networks:
      - elk_network

volumes:
  elasticsearch_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/data/elasticsearch_data'
      o: 'bind'
  filebeat_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/data/filebeat_data'
      o: 'bind'


networks:
  elk_network:
    driver: bridge